/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AdminIndexRouteImport } from './routes/_admin/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AdminI18nRouteImport } from './routes/_admin/i18n'
import { Route as AdminCrudRouteImport } from './routes/_admin/crud'

const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminI18nRoute = AdminI18nRouteImport.update({
  id: '/i18n',
  path: '/i18n',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCrudRoute = AdminCrudRouteImport.update({
  id: '/crud',
  path: '/crud',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/crud': typeof AdminCrudRoute
  '/i18n': typeof AdminI18nRoute
  '/auth/login': typeof AuthLoginRoute
}
export interface FileRoutesByTo {
  '/crud': typeof AdminCrudRoute
  '/i18n': typeof AdminI18nRoute
  '/auth/login': typeof AuthLoginRoute
  '/': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_admin/crud': typeof AdminCrudRoute
  '/_admin/i18n': typeof AdminI18nRoute
  '/auth/login': typeof AuthLoginRoute
  '/_admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/crud' | '/i18n' | '/auth/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/crud' | '/i18n' | '/auth/login' | '/'
  id:
    | '__root__'
    | '/_admin'
    | '/_admin/crud'
    | '/_admin/i18n'
    | '/auth/login'
    | '/_admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/i18n': {
      id: '/_admin/i18n'
      path: '/i18n'
      fullPath: '/i18n'
      preLoaderRoute: typeof AdminI18nRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/crud': {
      id: '/_admin/crud'
      path: '/crud'
      fullPath: '/crud'
      preLoaderRoute: typeof AdminCrudRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCrudRoute: typeof AdminCrudRoute
  AdminI18nRoute: typeof AdminI18nRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCrudRoute: AdminCrudRoute,
  AdminI18nRoute: AdminI18nRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
